service: bti-InfusionSoft-IT
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: EL-Set1-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to list, get and put and a file in the `conf-token` S3 bucket
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::conf-token/*"
    # Allow to put files in the `bti-dl-it` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::bti-dl-it"
        - "arn:aws:s3:::bti-dl-it/*"
    # Allow to scan and get the `bti_job_config_InfusionSoft_IT` DynamoDB table
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-west-2:004181835165:table/bti_job_config_InfusionSoft_IT"
    # Allow to scan, get, put and update the `bti_job_history_InfusionSoft_IT` DynamoDB table
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-west-2:004181835165:table/bti_job_history_InfusionSoft_IT"
functions:
  app:
    handler: app.extract_load_infusionSoft_it
    environment:
      aws_url:
      groupId: 1
      bucket: 
      encryption_secret_key: 
      client_id: 
      client_secret: 
      host: 

plugins:
  - serverless-python-requirements
