service: bti-SavedReport-JJ
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: EL-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to list, get and put and a file in the `conf-token` S3 bucket
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 
    # Allow to put files in the `bti-dl` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - 
functions:
  app:
    handler: app.EL_Saved_Report
    events:
      - schedule: cron(0 08 ? * * *)
    environment:
      encryption_secret_key: 
      bucket: 
      s3_staging_path: 
      s3_archive_path: 
      aws_url: 
      user_id: 
      client_id: 
      client_secret: 
      
      

plugins:
  - serverless-python-requirements
