service: bti-slack-notification

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  versionFunctions: false
  memorySize: 128
  region: us-west-2
  stage: dev

functions:
  email-notification:
    handler: bti-slack-notification.lambda_handler
  environment:
    webhook: 
plugins:
  - serverless-python-requirements

