service: bti-3CLogic-Historical
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: Aurora-Staging-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to put files in the `bti-dl` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::bti-dl"
        - "arn:aws:s3:::bti-dl/*"
functions:
  app:
    handler: app.handler
    environment:
     BUCKET: 
     HISTORICAL_FOLDER:  
     HOST: 
     USER_NAME: 
     PASSWORD: 
     DB_NAME:
     TABLE_NAME: 

plugins:
  - serverless-python-requirements
