service: bti-GoogleSheets
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: glue_trigger-dly-app
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
functions:
  app:
    handler: app.lambda_handler
    environment:
      Gluejobname: bti-Google-Sheets-Aurora-Staging-Publish-Set1-dly-app
      Gluejobname1: bti-Google-Sheets-Aurora-Staging-Publish-Set2-dly-app
plugins:
  - serverless-python-requirements

