service: bti-InfusionSoft-ZU
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: Aurora-Staging-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to put files in the `bti-dl-zu` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::bti-dl-zu"
        - "arn:aws:s3:::bti-dl-zu/*"
functions:
  app:
    handler: app.handler_zu
    environment:
      BUCKET:
      PUBLISH_FOLDER: 
      PUBLISH_PREFIX: 
      HOST: 
      USER_NAME: 
      PASSWORD: 
      DB_NAME: 

plugins:
  - serverless-python-requirements
