service: bti-GoogleSheets
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: EL-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to put files in the `bti-dl` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::bti-dl"
        - "arn:aws:s3:::bti-dl/*"
    # Allow to scan and get the `bti_config_google_sheets` DynamoDB table
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-west-2::table/bti_config_google_sheets"
functions:
  app:
    handler: app.extraction_load_google_sheets
    events:
      - schedule: cron(0 08 ? * * *)
    environment:
      aws_url: 
      groupId: 1
      bucket: 
      staging_folder: 
      staging_archive_folder: 
      staging_prefix: 

plugins:
  - serverless-python-requirements
