service: bti-email-notification

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  versionFunctions: false
  memorySize: 128
  region: us-west-2
  stage: dev

functions:
  email-notiication:
    handler: bti-dev-email.lambda_handler

plugins:
  -serverless-python-requirements

