service: bti-InfusionSoft-IT
provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  stage: T-new-dly
  deploymentBucket: bti-production-deployemnt
  iamRoleStatements:
    # Allow to put files in the `bti-dl-it` S3 bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::bti-dl-it"
        - "arn:aws:s3:::bti-dl-it/*"
functions:
  app:
    handler: app.handler_it
    environment:
      BUCKET: bti-dl-it
      STAGING_FOLDER: staging
      PUBLISH_FOLDER: publish
      PUBLISH_ARCHIVE_FOLDER: publish_archive
      STAGING_PREFIX: bti_infusionSoft/staging/
      PUBLISH_PREFIX: bti_infusionSoft/publish/
plugins:
  - serverless-python-requirements

